name: gme_time_tracker
description: "GME Time Tracker"

publish_to: "none"

version: 1.0.1+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  get: ^4.7.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  toastification: ^3.0.2
  intl: ^0.19.0
  syncfusion_flutter_charts: ^29.1.40
  syncfusion_flutter_pdf: ^29.1.40
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  device_info_plus: ^11.4.0
  permission_handler: ^12.0.0+1
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  media_store_plus: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/