// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nfrTnQGiqThiIp9q-8K1Yn5WDJ0suq4',
    appId: '1:907816878388:web:87f87e1e158cfeeaa12561',
    messagingSenderId: '907816878388',
    projectId: 'gme-time-tracker',
    authDomain: 'gme-time-tracker.firebaseapp.com',
    storageBucket: 'gme-time-tracker.firebasestorage.app',
    measurementId: 'G-39GD3ZN4PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtNqMBodLehjblnr9rJ7H4adRt8H3RbA',
    appId: '1:907816878388:android:6be26e8ad17efb9fa12561',
    messagingSenderId: '907816878388',
    projectId: 'gme-time-tracker',
    storageBucket: 'gme-time-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_yy4lD5iQqHKeTgtWijWtq9xBp_fRz4',
    appId: '1:907816878388:ios:66fa705982642410a12561',
    messagingSenderId: '907816878388',
    projectId: 'gme-time-tracker',
    storageBucket: 'gme-time-tracker.firebasestorage.app',
    iosBundleId: 'gme.timetracker.gmeTimeTracker',
  );
}
